name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.13.4']
        otp: ['25.0']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependancy cache
        id: mix-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Get Dependancies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Compile code
        run: mix compile --warnings-as-errors

  credo-checks:
    name: Credo
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.13.4']
        otp: ['25.0']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependancy cache
        id: mix-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Format check
        run: mix format --check-formatted
      - name: Static code analysis
        run: mix credo

  test:
    needs: build
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.13.4']
        otp: ['25.0']
    env:
      FB_PAGE_ACCESS_TOKEN: "fb-page-access-token"
      MESSENGER_VERIFY_TOKEN: "messenger-verify-token"
      MESSENGER_URL: "https://example.test.com"
      COINGECKO_URL: "https://api.test.com/api/v3"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependancy cache
        id: mix-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Run tests
        run: mix coveralls
  deploy:
    needs: [credo-checks, test]
    name: Prod Deploy
    runs-on: ubuntu-latest
    env:
      FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
      MESSENGER_VERIFY_TOKEN: ${{ secrets.MESSENGER_VERIFY_TOKEN }}
      MESSENGER_URL: ${{ secrets.MESSENGER_URL }}
      COINGECKO_URL: ${{ secrets.COINGECKO_URL }}
    steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only